### ISSUE TITLE
I'm using your api in https://github.com/hopdebee/bandcamp-player-evo

### ISSUE THREAD

**Issue by hopdebee** [patrickkfkan/bandcamp-fetch#1]
Hi Patrick, 

Wanted to say thanks for your api. I'm currently using it in [](https://github.com/hopdebee/bandcamp-player-evo) to scrape for genre-subgenre combinations. Later, I think i'll add possibilities to stream random albums from tag combinations. 

Thanks !
Helder

**Comment by patrickkfkan** [comment]
Thanks for showing support.
