### ISSUE TITLE
Track Duration Property Mismatch

### ISSUE THREAD

**Issue by Bonfire** [patrickkfkan/bandcamp-fetch#7]
I've found that when fetching Bandcamp Track information using `BandcampFetch().track.getInfo()`, track duration information is not returned. Setting `includeRawData: true` allows us to see that the duration property is not called `duration_secs` but rather `duration`, and can be found under `raw.basic.duration`. This duration property is not a number representing the duration in seconds but rather a string that tells how long the song is in hours, minutes, and seconds: "P00H05M19S"

Code responsible for parsing the duration from TrackInfo:
https://github.com/patrickkfkan/bandcamp-fetch/blob/7658926d0e5a11a54308b1cf4b1d29ddad47cc22/src/lib/track/TrackInfoParser.ts#L78
https://github.com/patrickkfkan/bandcamp-fetch/blob/7658926d0e5a11a54308b1cf4b1d29ddad47cc22/src/lib/utils/Parse.ts#L89

I believe there may have been a change at some point in the Bandcamp API that is causing this issue. Or possibly that some tracks return the usual `duration_secs` info, but other tracks return this weird `duration` string instead.

I have prepared a RunKit playground for you if you'd like to run some sample code that showcases this odd behavior. Also included is a workaround method that I've written to fetch the duration for the time being.
https://runkit.com/bonfire/bandcamp-fetch-duration

Thank you!

**Comment by patrickkfkan** [comment]
Hi there! Thanks for pointing this out. I have fixed this in v1.2.1. Please feel free to test it. Thanks!
