### ISSUE TITLE
Cookie - How?

### ISSUE THREAD

**Issue by masterdot** [patrickkfkan/bandcamp-fetch#9]
Hey there,

I did try to get the needed information, as your howto describes. But I don't find the needed information, using some values from the cookies is not working also. 
Was there a change and your howto is outdated?

Thanks for your help in advance :)

**Comment by masterdot** [comment]
Ahhhh... Ok, just take firefox and it will work with getting the cookie... 
Thanks for the plugin :)

**Comment by confluunt** [comment]
Absolutely no request contains my username whether I'm using Safari or Firefox on a Mac.
So which request URL should I get cookie from ?
